### ISSUE TITLE
Cannot run slimbookamdcontroller

### ISSUE THREAD

**Issue by Destroyer616** [slimbook/slimbookamdcontroller#5]
When i run the application in the terminal i got this error.
![Screenshot from 2021-08-12 11 12 55](https://user-images.githubusercontent.com/46772654/129144222-0e2340fd-fc67-4208-bb39-90bf956b67f2.png)

I am on Elementary Os 6 Odin.
My hardware: Huawei matebookd Ryzen 5 2500u Vega 8 graphics Kernel 5.11

**Comment by slimbook** [comment]
Should be fixed now,  can you test it?

**Comment by kentydotcom** [comment]
![Screenshot from 2021-11-17 20-51-09](https://user-images.githubusercontent.com/8278018/142204140-e46b6dc3-7ed2-4fc0-bd4b-9c606473f5df.png
![Screenshot from 2021-11-17 20-53-12](https://user-images.githubusercontent.com/8278018/142204290-53b898a5-1d37-4ed0-8a41-21f5f13c8745.png)

I am using Thinkpad E14 Gen2
Cannot start slimbookamdcontroller from menu or terminal.
)

**Comment by slimbook** [comment]
Thanks for reporting, we are working to locate the problem, last version is 0.3.7, please check that you have it updated.
